server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /suucilha
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: wilder26
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true